### ISSUE TITLE
Can no longer generate logo on QR code

### ISSUE THREAD

**Issue by MakawaMT** [sumimakito/AwesomeQRCode#27]
Ever since I updated to Android 8.0 I am unable to display the logo on the QR code.
It was working before on Android 7.0 and below.

**Comment by Marchuck** [comment]
I have also faced this issue, got logs like this:
```
D/skia: --- SkAndroidCodec::NewFromStream returned null
```

**Comment by MakawaMT** [comment]
@Marchuck were you able to resolve this issue? I have updated to 1.2.0 but I am still unable to generate a logo or background with an image in it

**Comment by MakawaMT** [comment]
issue was resolved after upgrading my gradle version and build tools
