### ISSUE TITLE
Error dependency instruction in readme

### ISSUE THREAD

**Issue by sighingnow** [SumiMakito/AwesomeQRCode#33]
The instruction about how to add library as dependency is not correct.

```
dependencies {
    compile 'com.github.SumiMakito:Awesome QR code:<LATEST_VERSION_NAME>'
}
```

Notice that there are spaces in `Awesome QR code`, however the repo name doesn't contains whitespace, then the jitpack URL is wrong, leading to errors when downloading this library from jitpack. The correct jitpack link should like:

```
https://jitpack.io/com/github/SumiMakito/AwesomeQRCode/1.2.0/AwesomeQRCode-1.2.0.pom
```

Rather than

```
https://jitpack.io/com/github/SumiMakito/Awesome%20QR%20code/1.2.0/Awesome%20QR%20code-1.2.0.pom
```

**Comment by sumimakito** [comment]
Thanks for reporting the issue. It is probably caused by a careless text replacement on the readme done by me. 😥
