### ISSUE TITLE
二维码可以调整纠错等级不？

### ISSUE THREAD

**Issue by zaihuishou** [SumiMakito/AwesomeQRCode#34]
想调整下生成的二维码的等级，不知道可以不，有提供方法吗？

**Comment by SumiMakito** [comment]
RenderOption 中的 `ecl` 是纠错等级相关，可选如下：
- ErrorCorrectionLevel.L
- ErrorCorrectionLevel.M
- ErrorCorrectionLevel.Q
- ErrorCorrectionLevel.H
```
val renderOption = RenderOption()
renderOption.ecl = ErrorCorrectionLevel.M
```
