### ISSUE TITLE
貌似不支持中文

### ISSUE THREAD

**Issue by loonggg** [SumiMakito/AwesomeQRCode#7]
如果填入的内容是中文的，那么貌似扫描出来的是问号乱码。

**Comment by SumiMakito** [comment]
应该是编码问题 我稍后修复 感谢反馈

**Comment by SumiMakito** [comment]
在编码前加入了 CHARACTER_SET => UTF-8 这组 Hint，Issue 已修复。
Reference commit: 4b9320fcd9056847680bb9f188b8e34b3338a1f8 .

**Comment by xingcxb** [comment]
在服务端接入应用的时候存在Android的包调用,无法使用
